version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  cassandra:
    image: cassandra:latest
    container_name: cassandra_container
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=TestCluster

  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    ports:
      - "7474:7474"  # Web interface
      - "7687:7687"  # Bolt protocol for queries
    environment:
      NEO4J_AUTH: neo4j/test
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  redis_data:
  mongo_data:
  cassandra_data:
  neo4j_data:
  neo4j_logs:
